[2024-05-06T12:40:17.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T12:40:17.788+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.insert_to_postgres manual__2024-05-06T12:40:05.394134+00:00 [queued]>
[2024-05-06T12:40:17.797+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.insert_to_postgres manual__2024-05-06T12:40:05.394134+00:00 [queued]>
[2024-05-06T12:40:17.798+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-05-06T12:40:17.812+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_to_postgres> on 2024-05-06 12:40:05.394134+00:00
[2024-05-06T12:40:17.818+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2739) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-06T12:40:17.820+0000] {standard_task_runner.py:63} INFO - Started process 2740 to run task
[2024-05-06T12:40:17.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'insert_to_postgres', 'manual__2024-05-06T12:40:05.394134+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmpkak66v_s']
[2024-05-06T12:40:17.822+0000] {standard_task_runner.py:91} INFO - Job 311: Subtask insert_to_postgres
[2024-05-06T12:40:17.862+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.insert_to_postgres manual__2024-05-06T12:40:05.394134+00:00 [running]> on host db2363de7199
[2024-05-06T12:40:17.948+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='insert_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T12:40:05.394134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T12:40:05.394134+00:00'
[2024-05-06T12:40:17.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T12:40:17.983+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-05-06T12:40:18.035+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-06T12:40:18.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T12:40:18.046+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=insert_to_postgres, execution_date=20240506T124005, start_date=20240506T124017, end_date=20240506T124018
[2024-05-06T12:40:18.074+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-06T12:40:18.093+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-06T12:40:18.095+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
